M newfiletype,

diff --git a/newfiletype b/newfiletype
--- a/newfiletype
+++ b/newfiletype
@@ -37,6 +37,7 @@ fi
 case $type in
 bash)
   echo '#!/bin/bash -euo pipefail' > $path
+  echo 'set -o pipefail' >> $path
   sudo chmod +x $path
 ;;
 python)
